sonar.projectKey=banking-recon
sonar.projectName=Banking Reconciliation Microservice
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/venv/**,**/__pycache__/**,**/tests/**,**/*.pyc

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3

# Per service
sonar.modules=transaction-service,statement-service,reconciliation-service

transaction-service.sonar.projectBaseDir=transaction-service
statement-service.sonar.projectBaseDir=statement-service
reconciliation-service.sonar.projectBaseDir=reconciliation-service