# sonar-project.properties

sonar.projectKey=banking-recon
sonar.projectName=Banking Reconciliation Microservice
sonar.python.version=3
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc

sonar.modules=transaction-service,statement-service,reconciliation-service

# ── Transaction Service ───────────────────────────────────
transaction-service.sonar.projectName=Transaction Service
transaction-service.sonar.projectBaseDir=transaction-service
transaction-service.sonar.sources=.
transaction-service.sonar.tests=tests          # ← relatif dari transaction-service/
transaction-service.sonar.test.inclusions=tests/test_*.py

# ── Statement Service ─────────────────────────────────────
statement-service.sonar.projectName=Statement Service
statement-service.sonar.projectBaseDir=statement-service
statement-service.sonar.sources=.
statement-service.sonar.tests=tests            # ← relatif dari statement-service/
statement-service.sonar.test.inclusions=tests/test_*.py

# ── Reconciliation Service ────────────────────────────────
reconciliation-service.sonar.projectName=Reconciliation Service
reconciliation-service.sonar.projectBaseDir=reconciliation-service
reconciliation-service.sonar.sources=.
reconciliation-service.sonar.tests=tests       # ← relatif dari reconciliation-service/
reconciliation-service.sonar.test.inclusions=tests/test_*.py